name: Deploy Site

on:
  push:
    branches: [main]

jobs:
  deploy-site-sync-gitee:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set node version to 14
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Install dependencies
        run: npm i

      - name: Build site
        run: npm run build

      - name: Deploy site
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-page
          folder: dist
